import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	docs: [
		{
			type: 'category',
			label: 'Start here',
			collapsed: false,
			items: ['index', 'guides/installation', 'guides/usage'],
		},
		{
			type: 'category',
			label: 'API Reference',
			// TypeDoc emits pages into docs/api from src/index.ts; Docusaurus scans them.
			link: { type: 'doc', id: 'api/index' },
			items: [{ type: 'autogenerated', dirName: 'api' }],
		},
		{
			type: 'category',
			label: 'Releases',
			items: ['changelog'],
		},
	],
}

export default sidebars
